spring:
  cloud:
    gateway:
      routes:
        - uri: https://google.com
          id: test-route
          predicates:
            - Path=/google/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                rate-limiter: "#{@rateLimiter}"
                key-resolver: "#{@keyResolver}"
                rate-limiter.limit: 3
