spring:
  cloud:
    gateway:
      routes:
        - uri: https://google.com
          predicates:
            - Path=/google/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                rate-limiter: "#{@hazelcastRateLimiter}"
                key-resolver: "#{@headerKeyResolver}"
                hazelcast-rate-limiter.limit: 3
